// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PersonaPoliticas.Datos;
using PersonaPoliticas.Models;
using System;
using System.Collections.Generic;

namespace PersonaPoliticas.Datos.Configurations
{
    public partial class HijoConfiguration : IEntityTypeConfiguration<Hijo>
    {
        public void Configure(EntityTypeBuilder<Hijo> entity)
        {
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.Carrera)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.IdPadreNavigation)
                .WithMany(p => p.Hijo)
                .HasForeignKey(d => d.IdPadre)
                .HasConstraintName("FK_Hijo_Padre");

            entity.HasOne(d => d.IdPersonaNavigation)
                .WithMany(p => p.Hijo)
                .HasForeignKey(d => d.IdPersona)
                .HasConstraintName("FK_Hijo_Persona");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Hijo> entity);
    }
}
