// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PersonaPoliticas.Datos;
using PersonaPoliticas.Models;
using System;
using System.Collections.Generic;

namespace PersonaPoliticas.Datos.Configurations
{
    public partial class PersonaHijoConfiguration : IEntityTypeConfiguration<PersonaHijo>
    {
        public void Configure(EntityTypeBuilder<PersonaHijo> entity)
        {
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.Nombre)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Genero)
                .WithMany(p => p.PersonaHijo)
                .HasForeignKey(d => d.GeneroId)
                .HasConstraintName("FK_PersonaHijo_Genero");

            entity.HasOne(d => d.Padre)
                .WithMany(p => p.PersonaHijo)
                .HasForeignKey(d => d.PadreId)
                .HasConstraintName("FK_PersonaHijo_PersonaPadre");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PersonaHijo> entity);
    }
}
